# NN Building blocks

predefined classes providing with basic functionality blocks designed with practice in mind

In [5]:
"""
Create a randomly initialized feed-forward network, with 2 inputs and 5 outputs and apply it to a float tensor
"""

import torch.nn as nn
import torch

l = nn.Linear(2, 5)
v = torch.FloatTensor([1,2])

l(v)

tensor([-0.4047,  0.7451,  0.1323, -1.1864, -0.9585], grad_fn=<AddBackward0>)

## nn.Module parameters

`parameters()`: returns an iterator of all variables that require gradient computation (module weights)

`zero_grad()`: initializes all gradietns of all parameters to zero

`to(device)`: CPU to GPU and vice versa

`state_dict`: Dictionary of all module parameters useful for model serialization (saving)

`load_state_dict()` initializes a network with a state dictionary

## Combine layers into others by piping

use `Sequential` to create multiple layers

In [7]:
"""
Define a three-layer NN with softmax on output applied along dimension 1 (dimension 0 is batch samples), rectified
linear layers (ReLU), and dropout
"""

s = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [16]:
# Push something through the network

s(torch.FloatTensor([[1,2]])) # minibatch flowing through network

tensor([[0.1049, 0.0778, 0.0782, 0.0949, 0.0949, 0.0949, 0.1553, 0.1003, 0.1038,
         0.0949]], grad_fn=<SoftmaxBackward>)

## Custom layers

By subclassing `nn.Module`, you can create your own building blocks, which can stack together, reused later, and integrated into the PyTorch framework flawlessly

In [20]:
"""
forward() must be overridden to apply network
"""

class OurModule(nn.Module):
    def __init__(self, num_inputs, num_classes, dropout_prob=0.3):
        super(OurModule, self).__init__()
        self.pipe = nn.Sequential(
            nn.Linear(num_inputs, 5),
            nn.ReLU(),
            nn.Linear(5, 20),
            nn.ReLU(),
            nn.Linear(20, num_classes),
            nn.Dropout(p=dropout_prob),
            nn.Softmax(dim=1)
        )
        
    def forward(self, x):
        return self.pipe(x)
    
net = OurModule(num_inputs=2, num_classes=3)
v = torch.FloatTensor([[2, 3]])
out = net(v)
print(net)
print(out)

OurModule(
  (pipe): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
    (5): Dropout(p=0.3, inplace=False)
    (6): Softmax(dim=1)
  )
)
tensor([[0.4634, 0.2562, 0.2803]], grad_fn=<SoftmaxBackward>)


## Summary

PyTorch has the ability to create multiple layers of networks, you can override the default `Module` and create your own properties/features/functions